### ISSUE TITLE
How to support macos builds given tool renaming

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/fastjet-feedstock#10]
In PR #9 all the macos build fail with

```
  On Mac OSX, the GNU libtool and libtoolize scripts, renamed
  glibtol and glibtoolize respectively by Apple to avoid
  conflict with Apple-provided libtool, should be used.

  They should be already installed, together with Apple developer tools,
  in /usr/bin. If you see this message, they are not.
```

even though

https://github.com/conda-forge/fastjet-feedstock/blob/f73dac77a3b5f1e543620921dace6de8e7bc9496/recipe/meta.yaml#L31

has a macos install.

In https://github.com/conda-forge/fastjet-feedstock/blob/f73dac77a3b5f1e543620921dace6de8e7bc9496/recipe/meta.yaml#L31

@lgray had gotten around this (in PR https://github.com/scikit-hep/fastjet/pull/134) with

```yaml
      - name: Install compiler tools on macOS
        if: runner.os == 'macOS'
        run: |
          brew install make automake swig gmp mpfr boost
          export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
```

but everything that needs to be installed needs to be specified in the `meta.yaml` for `conda-forge` and should already be in the build requirements.

https://github.com/conda-forge/fastjet-feedstock/blob/f73dac77a3b5f1e543620921dace6de8e7bc9496/recipe/meta.yaml#L22-L34

How can this get addressed? Or does this required patching the build system for these existing `fastjet` releases?

cc @henryiii and @chrisburr if they have any ideas.
